# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 30, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(70, 100, 311, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 81, 16))
        self.label_3.setObjectName("label_3")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(100, 140, 281, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_3 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_3.setGeometry(QtCore.QRect(100, 180, 281, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 220, 141, 16))
        self.label_5.setObjectName("label_5")
        self.comboBox_4 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_4.setGeometry(QtCore.QRect(150, 220, 231, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 260, 211, 16))
        self.label_6.setObjectName("label_6")
        self.comboBox_5 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_5.setGeometry(QtCore.QRect(220, 260, 161, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.setItemText(0, "")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 131, 16))
        self.label_7.setObjectName("label_7")
        self.comboBox_6 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_6.setGeometry(QtCore.QRect(150, 300, 231, 22))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.setItemText(0, "")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(150, 520, 47, 13))
        self.label_8.setObjectName("label_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 340, 75, 23))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Интимки от создателя"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Ириска"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Алиса"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Девушка создателя(пока не открыто)"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Если не Ириска и не Алиса закройте приложение!"))
        self.label_2.setText(_translate("MainWindow", "Ваше имя"))
        self.label_3.setText(_translate("MainWindow", "Вам больше 18?"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Да!"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Тогда вы точно не должны пользоваться этим!"))
        self.label_4.setText(_translate("MainWindow", "Кол-во одежы"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Полностью одет)"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Некоторые участки обнажены)))"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Полностью раздет!))))))"))
        self.label_5.setText(_translate("MainWindow", "Интересуемая часть тела"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Руки"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "Грудь"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "Пресс"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "Попа"))
        self.comboBox_4.setItemText(5, _translate("MainWindow", "Ножки"))
        self.comboBox_4.setItemText(6, _translate("MainWindow", "Лицо"))
        self.comboBox_4.setItemText(7, _translate("MainWindow", "ПИПИСЬКА!!!!!!"))
        self.label_6.setText(_translate("MainWindow", "Состояние части тела на фотокарточке"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Напряжено"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Расслабленно"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "ВОЗБУЖДЕНО!!!!"))
        self.label_7.setText(_translate("MainWindow", "Состояние фотокарточки"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Старая"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Новая"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Хочу видео звонок)))"))
        self.label_8.setText(_translate("MainWindow", "Beta v1.0"))
        self.pushButton.setText(_translate("MainWindow", "Создать!"))
