# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import configparser
import ini


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        config = configparser.ConfigParser()
        config.read("RunTime.ini")
        OurTime = config.get("Run_Time","ourtime")
        if OurTime == "0":#RunTime time
            print('RunTime')
            W_H = tuple(map(int,config.get("Run_Time","mainwindow").split()))
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(W_H[0],W_H[1]) #W = 315 H = 420
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            l_param = tuple(map(int,config.get('Run_Time','label').split()))
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(l_param[0], l_param[1], l_param[2], l_param[3]))
            font = QtGui.QFont()
            font.setPointSize(18)
            self.label.setFont(font)
            self.label.setObjectName("label")
            pB_param = tuple(map(int,config.get('Run_Time','pushButton').split()))
            self.pushButton = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton.setGeometry(QtCore.QRect(pB_param[0], pB_param[1], pB_param[2], pB_param[3]))
            self.pushButton.setObjectName("pushButton")
            pB2_param = tuple(map(int,config.get('Run_Time','pushButton_2').split()))
            self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_2.setGeometry(QtCore.QRect(pB2_param[0], pB2_param[1], pB2_param[2], pB2_param[3]))
            self.pushButton_2.setObjectName("pushButton_2")
            pB3_param = tuple(map(int,config.get('Run_Time','pushButton_3').split()))
            self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_3.setGeometry(QtCore.QRect(pB3_param[0], pB3_param[1], pB3_param[2], pB3_param[3]))
            self.pushButton_3.setObjectName("pushButton_3")
            pB4_param = tuple(map(int,config.get('Run_Time','pushButton_4').split()))
            self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_4.setGeometry(QtCore.QRect(pB4_param[0], pB4_param[1], pB4_param[2], pB4_param[3]))
            self.pushButton_4.setObjectName("pushButton_4")
            pB5_param = tuple(map(int,config.get('Run_Time','pushButton_5').split()))
            self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_5.setGeometry(QtCore.QRect(pB5_param[0], pB5_param[1], pB5_param[2], pB5_param[3]))
            self.pushButton_5.setObjectName("pushButton_5")
            pB6_param = tuple(map(int,config.get('Run_Time','pushButton_6').split()))
            self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_6.setGeometry(QtCore.QRect(pB6_param[0], pB6_param[1], pB6_param[2], pB6_param[3]))
            self.pushButton_6.setObjectName("pushButton_6")
            pB7_param = tuple(map(int,config.get('Run_Time','pushButton_7').split()))
            self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_7.setGeometry(QtCore.QRect(pB7_param[0], pB7_param[1], pB7_param[2], pB7_param[3]))
            self.pushButton_7.setObjectName("pushButton_7")
            l2_param = tuple(map(int,config.get('Run_Time','label_2').split()))
            self.label_2 = QtWidgets.QLabel(self.centralwidget)
            self.label_2.setGeometry(QtCore.QRect(l2_param[0], l2_param[1], l2_param[2], l2_param[3]))
            self.label_2.setObjectName("label_2")
            l3_param = tuple(map(int,config.get('Run_Time','label_3').split()))
            self.label_3 = QtWidgets.QLabel(self.centralwidget)
            self.label_3.setGeometry(QtCore.QRect(l3_param[0], l3_param[1], l3_param[2], l3_param[3]))
            self.label_3.setObjectName("label_3")
            l4_param = tuple(map(int,config.get('Run_Time','label_4').split()))
            self.label_4 = QtWidgets.QLabel(self.centralwidget)
            self.label_4.setGeometry(QtCore.QRect(l4_param[0], l4_param[1], l4_param[2], l4_param[3]))
            self.label_4.setObjectName("label_4")
            l5_param = tuple(map(int,config.get('Run_Time','label_5').split()))
            self.label_5 = QtWidgets.QLabel(self.centralwidget)
            self.label_5.setGeometry(QtCore.QRect(l5_param[0], l5_param[1], l5_param[2], l5_param[3]))
            self.label_5.setObjectName("label_5")
            l6_param = tuple(map(int,config.get('Run_Time','label_6').split()))
            self.label_6 = QtWidgets.QLabel(self.centralwidget)
            self.label_6.setGeometry(QtCore.QRect(l6_param[0], l6_param[1], l6_param[2], l6_param[3]))
            self.label_6.setObjectName("label_6")
            self.label_7 = QtWidgets.QLabel(self.centralwidget)
            self.label_7.setGeometry(QtCore.QRect(150, 330, 121, 31))
            self.label_7.setObjectName("label_7")
            self.label_8 = QtWidgets.QLabel(self.centralwidget)
            self.label_8.setGeometry(QtCore.QRect(150, 380, 121, 31))
            self.label_8.setObjectName("label_8")
            pTE_param = tuple(map(int,config.get('Run_Time','plainTextEdit').split()))
            self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit.setGeometry(QtCore.QRect(pTE_param[0],pTE_param[1],pTE_param[2],pTE_param[3]))
            self.plainTextEdit.setObjectName("plainTextEdit")
            pTE2_param = tuple(map(int,config.get('Run_Time','plainTextEdit_2').split()))
            self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_2.setGeometry(QtCore.QRect(pTE2_param[0],pTE2_param[1],pTE2_param[2],pTE2_param[3]))
            self.plainTextEdit_2.setObjectName("plainTextEdit_2")
            pTE3_param = tuple(map(int,config.get('Run_Time','plainTextEdit_3').split()))
            self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_3.setGeometry(QtCore.QRect(pTE3_param[0],pTE3_param[1],pTE3_param[2],pTE3_param[3]))
            self.plainTextEdit_3.setObjectName("plainTextEdit_3")
            pTE4_param = tuple(map(int,config.get('Run_Time','plainTextEdit_4').split()))
            self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_4.setGeometry(QtCore.QRect(pTE4_param[0],pTE4_param[1],pTE4_param[2],pTE4_param[3]))
            self.plainTextEdit_4.setObjectName("plainTextEdit_4")
            pTE5_param = tuple(map(int,config.get('Run_Time','plainTextEdit_5').split()))
            self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_5.setGeometry(QtCore.QRect(pTE5_param[0],pTE5_param[1],pTE5_param[2],pTE5_param[3]))
            self.plainTextEdit_5.setObjectName("plainTextEdit_5")
            pTE6_param = tuple(map(int,config.get('Run_Time','plainTextEdit_6').split()))
            self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_6.setGeometry(QtCore.QRect(pTE6_param[0],pTE6_param[1],pTE6_param[2],pTE6_param[3]))
            self.plainTextEdit_6.setObjectName("plainTextEdit_6")
            pTE7_param = tuple(map(int,config.get('Run_Time','plainTextEdit_7').split()))
            self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_7.setGeometry(QtCore.QRect(pTE7_param[0],pTE7_param[1],pTE7_param[2],pTE7_param[3]))
            self.plainTextEdit_7.setObjectName("plainTextEdit_7")
            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)
        elif OurTime == "1":
            print('DesignTime')
            MainWindow.setObjectName("MainWindow")
            MainWindow.resize(315,550) #W = 315 H = 420
            self.centralwidget = QtWidgets.QWidget(MainWindow)
            self.centralwidget.setObjectName("centralwidget")
            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(70, 20, 61, 41))
            font = QtGui.QFont()
            font.setPointSize(18)
            self.label.setFont(font)
            self.label.setObjectName("label")
            self.pushButton = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton.setGeometry(QtCore.QRect(20, 440, 81, 23))
            self.pushButton.setObjectName("pushButton")
            self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_2.setGeometry(QtCore.QRect(110, 440, 81, 23))
            self.pushButton_2.setObjectName("pushButton_2")
            self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_3.setGeometry(QtCore.QRect(200, 440, 81, 23))
            self.pushButton_3.setObjectName("pushButton_3")
            self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_4.setGeometry(QtCore.QRect(110, 470, 81, 23))
            self.pushButton_4.setObjectName("pushButton_4")
            self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_5.setGeometry(QtCore.QRect(20, 470, 81, 23))
            self.pushButton_5.setObjectName("pushButton_5")
            self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_6.setGeometry(QtCore.QRect(200, 470, 81, 23))
            self.pushButton_6.setObjectName("pushButton_6")
            self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
            self.pushButton_7.setGeometry(QtCore.QRect(110, 500, 81, 23))
            self.pushButton_7.setObjectName("pushButton_7")
            self.label_2 = QtWidgets.QLabel(self.centralwidget)
            self.label_2.setGeometry(QtCore.QRect(150, 70, 121, 31))
            self.label_2.setObjectName("label_2")
            self.label_3 = QtWidgets.QLabel(self.centralwidget)
            self.label_3.setGeometry(QtCore.QRect(150, 120, 121, 31))
            self.label_3.setObjectName("label_3")
            self.label_4 = QtWidgets.QLabel(self.centralwidget)
            self.label_4.setGeometry(QtCore.QRect(150, 180, 121, 31))
            self.label_4.setObjectName("label_4")
            self.label_5 = QtWidgets.QLabel(self.centralwidget)
            self.label_5.setGeometry(QtCore.QRect(150, 230, 121, 31))
            self.label_5.setObjectName("label_5")
            self.label_6 = QtWidgets.QLabel(self.centralwidget)
            self.label_6.setGeometry(QtCore.QRect(150, 280, 121, 31))
            self.label_6.setObjectName("label_6")
            self.label_7 = QtWidgets.QLabel(self.centralwidget)
            self.label_7.setGeometry(QtCore.QRect(150, 330, 121, 31))
            self.label_7.setObjectName("label_7")
            self.label_8 = QtWidgets.QLabel(self.centralwidget)
            self.label_8.setGeometry(QtCore.QRect(150, 380, 121, 31))
            self.label_8.setObjectName("label_8")
            self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit.setGeometry(QtCore.QRect(20, 70, 104, 31))
            self.plainTextEdit.setObjectName("plainTextEdit")
            self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_2.setGeometry(QtCore.QRect(20, 120, 104, 31))
            self.plainTextEdit_2.setObjectName("plainTextEdit_2")
            self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_3.setGeometry(QtCore.QRect(20, 180, 104, 31))
            self.plainTextEdit_3.setObjectName("plainTextEdit_3")
            self.plainTextEdit_4 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_4.setGeometry(QtCore.QRect(20, 240, 104, 31))
            self.plainTextEdit_4.setObjectName("plainTextEdit_4")
            self.plainTextEdit_5 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_5.setGeometry(QtCore.QRect(20, 290, 104, 31))
            self.plainTextEdit_5.setObjectName("plainTextEdit_5")
            self.plainTextEdit_6 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_6.setGeometry(QtCore.QRect(20, 340, 104, 31))
            self.plainTextEdit_6.setObjectName("plainTextEdit_6")
            self.plainTextEdit_7 = QtWidgets.QPlainTextEdit(self.centralwidget)
            self.plainTextEdit_7.setGeometry(QtCore.QRect(20, 390, 104, 31))
            self.plainTextEdit_7.setObjectName("plainTextEdit_7")
            MainWindow.setCentralWidget(self.centralwidget)
            self.statusbar = QtWidgets.QStatusBar(MainWindow)
            self.statusbar.setObjectName("statusbar")
            MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "2_lab"))
        self.pushButton.setText(_translate("MainWindow", "Очистить"))
        self.pushButton_2.setText(_translate("MainWindow", "Отменить"))
        self.pushButton_3.setText(_translate("MainWindow", "Восстановить"))
        self.pushButton_4.setText(_translate("MainWindow", "Закрыть"))
        self.pushButton_5.setText(_translate("MainWindow", "Редачить"))
        self.pushButton_6.setText(_translate("MainWindow", "Показать"))
        self.pushButton_7.setText(_translate("MainWindow", "Добавить"))
        self.label_2.setText(_translate("MainWindow", "Фамилия"))
        self.label_3.setText(_translate("MainWindow", "Имя"))
        self.label_4.setText(_translate("MainWindow", "Пол"))
        self.label_5.setText(_translate("MainWindow", "Дата рождения"))
        self.label_6.setText(_translate("MainWindow", "Адрес"))
        self.label_7.setText(_translate("MainWindow", "Должность"))
        self.label_8.setText(_translate("MainWindow", "Место жительства"))
